/**
 * Contaxy API
 * Functionality to create and manage projects, services, jobs, and files.
 *
 * The version of the OpenAPI document: 0.0.22
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BodyIntrospectToken model module.
 * @module model/BodyIntrospectToken
 * @version 0.0.22
 */
class BodyIntrospectToken {
  /**
   * Constructs a new <code>BodyIntrospectToken</code>.
   * @alias module:model/BodyIntrospectToken
   * @param token {String} The token that should be instrospected.
   */
  constructor(token) {
    BodyIntrospectToken.initialize(this, token);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, token) {
    obj['token'] = token;
  }

  /**
   * Constructs a <code>BodyIntrospectToken</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BodyIntrospectToken} obj Optional instance to populate.
   * @return {module:model/BodyIntrospectToken} The populated <code>BodyIntrospectToken</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BodyIntrospectToken();

      if (data.hasOwnProperty('token')) {
        obj['token'] = ApiClient.convertToType(data['token'], 'String');
      }
      if (data.hasOwnProperty('token_type_hint')) {
        obj['token_type_hint'] = ApiClient.convertToType(
          data['token_type_hint'],
          'String'
        );
      }
    }
    return obj;
  }
}

/**
 * The token that should be instrospected.
 * @member {String} token
 */
BodyIntrospectToken.prototype['token'] = undefined;

/**
 * A hint about the type of the token submitted for introspection (e.g. `access_token`, `id_token` and `refresh_token`).
 * @member {String} token_type_hint
 */
BodyIntrospectToken.prototype['token_type_hint'] = undefined;

export default BodyIntrospectToken;
