/**
 * Contaxy API
 * Functionality to create and manage projects, services, jobs, and files.
 *
 * The version of the OpenAPI document: 0.0.22
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * Enum class ExtensionType.
 * @enum {}
 * @readonly
 */
export default class ExtensionType {
  /**
   * value: "user-extension"
   * @const
   */
  'user-extension' = 'user-extension';

  /**
   * value: "project-extension"
   * @const
   */
  'project-extension' = 'project-extension';

  /**
   * Returns a <code>ExtensionType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ExtensionType} The enum <code>ExtensionType</code> value.
   */
  static constructFromObject(object) {
    return object;
  }
}
