{{- if .Values.integratedPostgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "machine-learning-lab.fullname" . }}-postgres
  labels:
    {{- include "machine-learning-lab.labels" . | nindent 4 }}
    ctxy.deploymentType: "core"
    ctxy.deploymentName: "postgres"
spec:
  type: {{ .Values.integratedPostgres.service.type }}
  ports:
    - port: {{ .Values.integratedPostgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "machine-learning-lab.selectorLabels" . | nindent 4 }}
    ctxy.deploymentType: "core"
    ctxy.deploymentName: "postgres"
{{- end }}
