{{- if .Values.integratedPostgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "machine-learning-lab.fullname" . }}-postgres
  labels:
    {{- include "machine-learning-lab.labels" . | nindent 4 }}
    ctxy.deploymentType: "core"
    ctxy.deploymentName: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "machine-learning-lab.selectorLabels" . | nindent 6 }}
      ctxy.deploymentType: "core"
      ctxy.deploymentName: "postgres"
  template:
    metadata:
      name: {{ include "machine-learning-lab.fullname" . }}-postgres
      {{- with .Values.integratedPostgres.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "machine-learning-lab.selectorLabels" . | nindent 8 }}
        ctxy.deploymentType: "core"
        ctxy.deploymentName: "postgres"
    spec:
      {{- with .Values.integratedPostgres.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.integratedPostgres.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.integratedPostgres.image.repository }}:{{ .Values.integratedPostgres.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.integratedPostgres.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.integratedPostgres.containerSecurityContext | nindent 12 }}
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "{{ .Values.integratedPostgres.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.integratedPostgres.password }}"
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.integratedPostgres.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
              subPath: postgres
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "machine-learning-lab.fullname" . }}-postgres-data
      {{- with .Values.integratedPostgres.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.integratedPostgres.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.integratedPostgres.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
