# coding: utf-8

"""
    ML Lab Service

    Functionality to create and manage Lab projects, services, datasets, models, and experiments.  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class LabService(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'docker_id': 'str',
        'docker_name': 'str',
        'docker_image': 'str',
        'admin_link': 'str',
        'started_at': 'int',
        'status': 'str',
        'feature_type': 'str',
        'configuration': 'dict(str, str)',
        'labels': 'dict(str, str)',
        'is_healthy': 'bool',
        'modified_at': 'int',
        'connection_port': 'int',
        'exposed_ports': 'list[int]'
    }

    attribute_map = {
        'name': 'name',
        'docker_id': 'dockerId',
        'docker_name': 'dockerName',
        'docker_image': 'dockerImage',
        'admin_link': 'adminLink',
        'started_at': 'startedAt',
        'status': 'status',
        'feature_type': 'featureType',
        'configuration': 'configuration',
        'labels': 'labels',
        'is_healthy': 'isHealthy',
        'modified_at': 'modifiedAt',
        'connection_port': 'connectionPort',
        'exposed_ports': 'exposedPorts'
    }

    def __init__(self, name=None, docker_id=None, docker_name=None, docker_image=None, admin_link=None, started_at=None, status=None, feature_type=None, configuration=None, labels=None, is_healthy=None, modified_at=None, connection_port=None, exposed_ports=None):  # noqa: E501
        """LabService - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._docker_id = None
        self._docker_name = None
        self._docker_image = None
        self._admin_link = None
        self._started_at = None
        self._status = None
        self._feature_type = None
        self._configuration = None
        self._labels = None
        self._is_healthy = None
        self._modified_at = None
        self._connection_port = None
        self._exposed_ports = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if docker_id is not None:
            self.docker_id = docker_id
        if docker_name is not None:
            self.docker_name = docker_name
        if docker_image is not None:
            self.docker_image = docker_image
        if admin_link is not None:
            self.admin_link = admin_link
        if started_at is not None:
            self.started_at = started_at
        if status is not None:
            self.status = status
        if feature_type is not None:
            self.feature_type = feature_type
        if configuration is not None:
            self.configuration = configuration
        if labels is not None:
            self.labels = labels
        if is_healthy is not None:
            self.is_healthy = is_healthy
        if modified_at is not None:
            self.modified_at = modified_at
        if connection_port is not None:
            self.connection_port = connection_port
        if exposed_ports is not None:
            self.exposed_ports = exposed_ports

    @property
    def name(self):
        """Gets the name of this LabService.  # noqa: E501


        :return: The name of this LabService.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LabService.


        :param name: The name of this LabService.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def docker_id(self):
        """Gets the docker_id of this LabService.  # noqa: E501


        :return: The docker_id of this LabService.  # noqa: E501
        :rtype: str
        """
        return self._docker_id

    @docker_id.setter
    def docker_id(self, docker_id):
        """Sets the docker_id of this LabService.


        :param docker_id: The docker_id of this LabService.  # noqa: E501
        :type: str
        """

        self._docker_id = docker_id

    @property
    def docker_name(self):
        """Gets the docker_name of this LabService.  # noqa: E501


        :return: The docker_name of this LabService.  # noqa: E501
        :rtype: str
        """
        return self._docker_name

    @docker_name.setter
    def docker_name(self, docker_name):
        """Sets the docker_name of this LabService.


        :param docker_name: The docker_name of this LabService.  # noqa: E501
        :type: str
        """

        self._docker_name = docker_name

    @property
    def docker_image(self):
        """Gets the docker_image of this LabService.  # noqa: E501


        :return: The docker_image of this LabService.  # noqa: E501
        :rtype: str
        """
        return self._docker_image

    @docker_image.setter
    def docker_image(self, docker_image):
        """Sets the docker_image of this LabService.


        :param docker_image: The docker_image of this LabService.  # noqa: E501
        :type: str
        """

        self._docker_image = docker_image

    @property
    def admin_link(self):
        """Gets the admin_link of this LabService.  # noqa: E501


        :return: The admin_link of this LabService.  # noqa: E501
        :rtype: str
        """
        return self._admin_link

    @admin_link.setter
    def admin_link(self, admin_link):
        """Sets the admin_link of this LabService.


        :param admin_link: The admin_link of this LabService.  # noqa: E501
        :type: str
        """

        self._admin_link = admin_link

    @property
    def started_at(self):
        """Gets the started_at of this LabService.  # noqa: E501


        :return: The started_at of this LabService.  # noqa: E501
        :rtype: int
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this LabService.


        :param started_at: The started_at of this LabService.  # noqa: E501
        :type: int
        """

        self._started_at = started_at

    @property
    def status(self):
        """Gets the status of this LabService.  # noqa: E501


        :return: The status of this LabService.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this LabService.


        :param status: The status of this LabService.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def feature_type(self):
        """Gets the feature_type of this LabService.  # noqa: E501


        :return: The feature_type of this LabService.  # noqa: E501
        :rtype: str
        """
        return self._feature_type

    @feature_type.setter
    def feature_type(self, feature_type):
        """Sets the feature_type of this LabService.


        :param feature_type: The feature_type of this LabService.  # noqa: E501
        :type: str
        """

        self._feature_type = feature_type

    @property
    def configuration(self):
        """Gets the configuration of this LabService.  # noqa: E501


        :return: The configuration of this LabService.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration):
        """Sets the configuration of this LabService.


        :param configuration: The configuration of this LabService.  # noqa: E501
        :type: dict(str, str)
        """

        self._configuration = configuration

    @property
    def labels(self):
        """Gets the labels of this LabService.  # noqa: E501


        :return: The labels of this LabService.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this LabService.


        :param labels: The labels of this LabService.  # noqa: E501
        :type: dict(str, str)
        """

        self._labels = labels

    @property
    def is_healthy(self):
        """Gets the is_healthy of this LabService.  # noqa: E501


        :return: The is_healthy of this LabService.  # noqa: E501
        :rtype: bool
        """
        return self._is_healthy

    @is_healthy.setter
    def is_healthy(self, is_healthy):
        """Sets the is_healthy of this LabService.


        :param is_healthy: The is_healthy of this LabService.  # noqa: E501
        :type: bool
        """

        self._is_healthy = is_healthy

    @property
    def modified_at(self):
        """Gets the modified_at of this LabService.  # noqa: E501


        :return: The modified_at of this LabService.  # noqa: E501
        :rtype: int
        """
        return self._modified_at

    @modified_at.setter
    def modified_at(self, modified_at):
        """Sets the modified_at of this LabService.


        :param modified_at: The modified_at of this LabService.  # noqa: E501
        :type: int
        """

        self._modified_at = modified_at

    @property
    def connection_port(self):
        """Gets the connection_port of this LabService.  # noqa: E501


        :return: The connection_port of this LabService.  # noqa: E501
        :rtype: int
        """
        return self._connection_port

    @connection_port.setter
    def connection_port(self, connection_port):
        """Sets the connection_port of this LabService.


        :param connection_port: The connection_port of this LabService.  # noqa: E501
        :type: int
        """

        self._connection_port = connection_port

    @property
    def exposed_ports(self):
        """Gets the exposed_ports of this LabService.  # noqa: E501


        :return: The exposed_ports of this LabService.  # noqa: E501
        :rtype: list[int]
        """
        return self._exposed_ports

    @exposed_ports.setter
    def exposed_ports(self, exposed_ports):
        """Sets the exposed_ports of this LabService.


        :param exposed_ports: The exposed_ports of this LabService.  # noqa: E501
        :type: list[int]
        """

        self._exposed_ports = exposed_ports

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LabService, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LabService):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
