/*
 * ML Lab Service
 * Functionality to create and manage Lab projects, services, datasets, models, and experiments.
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MlLabService) {
      root.MlLabService = {};
    }
    root.MlLabService.ExperimentResources = factory(root.MlLabService.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ExperimentResources model module.
   * @module model/ExperimentResources
   * @version 2.2.0-SNAPSHOT
   */

  /**
   * Constructs a new <code>ExperimentResources</code>.
   * @alias module:model/ExperimentResources
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ExperimentResources</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExperimentResources} obj Optional instance to populate.
   * @return {module:model/ExperimentResources} The populated <code>ExperimentResources</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], ['String']);
      if (data.hasOwnProperty('artifacts'))
        obj.artifacts = ApiClient.convertToType(data['artifacts'], ['String']);
      if (data.hasOwnProperty('output'))
        obj.output = ApiClient.convertToType(data['output'], ['String']);
      if (data.hasOwnProperty('experimentDir'))
        obj.experimentDir = ApiClient.convertToType(data['experimentDir'], 'String');
      if (data.hasOwnProperty('experimentBackup'))
        obj.experimentBackup = ApiClient.convertToType(data['experimentBackup'], 'String');
      if (data.hasOwnProperty('sourceCode'))
        obj.sourceCode = ApiClient.convertToType(data['sourceCode'], 'String');
      if (data.hasOwnProperty('sourceScript'))
        obj.sourceScript = ApiClient.convertToType(data['sourceScript'], 'String');
      if (data.hasOwnProperty('tensorboardLogs'))
        obj.tensorboardLogs = ApiClient.convertToType(data['tensorboardLogs'], 'String');
      if (data.hasOwnProperty('stdout'))
        obj.stdout = ApiClient.convertToType(data['stdout'], 'String');
    }
    return obj;
  }

  /**
   * @member {Array.<String>} input
   */
  exports.prototype.input = undefined;

  /**
   * @member {Array.<String>} artifacts
   */
  exports.prototype.artifacts = undefined;

  /**
   * @member {Array.<String>} output
   */
  exports.prototype.output = undefined;

  /**
   * @member {String} experimentDir
   */
  exports.prototype.experimentDir = undefined;

  /**
   * @member {String} experimentBackup
   */
  exports.prototype.experimentBackup = undefined;

  /**
   * @member {String} sourceCode
   */
  exports.prototype.sourceCode = undefined;

  /**
   * @member {String} sourceScript
   */
  exports.prototype.sourceScript = undefined;

  /**
   * @member {String} tensorboardLogs
   */
  exports.prototype.tensorboardLogs = undefined;

  /**
   * @member {String} stdout
   */
  exports.prototype.stdout = undefined;

  return exports;

}));
