/*
 * ML Lab Service
 * Functionality to create and manage Lab projects, services, datasets, models, and experiments.
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MlLabService) {
      root.MlLabService = {};
    }
    root.MlLabService.GitInfo = factory(root.MlLabService.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GitInfo model module.
   * @module model/GitInfo
   * @version 2.2.0-SNAPSHOT
   */

  /**
   * Constructs a new <code>GitInfo</code>.
   * @alias module:model/GitInfo
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>GitInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GitInfo} obj Optional instance to populate.
   * @return {module:model/GitInfo} The populated <code>GitInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('commit'))
        obj.commit = ApiClient.convertToType(data['commit'], 'String');
      if (data.hasOwnProperty('remoteUrl'))
        obj.remoteUrl = ApiClient.convertToType(data['remoteUrl'], 'String');
      if (data.hasOwnProperty('branch'))
        obj.branch = ApiClient.convertToType(data['branch'], 'String');
      if (data.hasOwnProperty('userName'))
        obj.userName = ApiClient.convertToType(data['userName'], 'String');
      if (data.hasOwnProperty('userEmail'))
        obj.userEmail = ApiClient.convertToType(data['userEmail'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} commit
   */
  exports.prototype.commit = undefined;

  /**
   * @member {String} remoteUrl
   */
  exports.prototype.remoteUrl = undefined;

  /**
   * @member {String} branch
   */
  exports.prototype.branch = undefined;

  /**
   * @member {String} userName
   */
  exports.prototype.userName = undefined;

  /**
   * @member {String} userEmail
   */
  exports.prototype.userEmail = undefined;

  return exports;

}));
