/**
 * ML Lab Service
 * Functionality to create and manage Lab projects, services, datasets, models, and experiments.
 *
 * OpenAPI spec version: 0.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LabInfo from './LabInfo';
import UnifiedErrorMessage from './UnifiedErrorMessage';
import UnifiedFormatMetadata from './UnifiedFormatMetadata';

/**
 * The LabInfoResponse model module.
 * @module model/LabInfoResponse
 * @version 0.2.0-SNAPSHOT
 */
export default class LabInfoResponse {
  /**
   * Constructs a new <code>LabInfoResponse</code>.
   * @alias module:model/LabInfoResponse
   * @class
   */

  constructor() {}

  /**
   * Constructs a <code>LabInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LabInfoResponse} obj Optional instance to populate.
   * @return {module:model/LabInfoResponse} The populated <code>LabInfoResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LabInfoResponse();

      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = UnifiedFormatMetadata.constructFromObject(
          data['metadata']
        );
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = LabInfo.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('errors')) {
        obj['errors'] = UnifiedErrorMessage.constructFromObject(data['errors']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/UnifiedFormatMetadata} metadata
   */
  metadata = undefined;
  /**
   * @member {module:model/LabInfo} data
   */
  data = undefined;
  /**
   * @member {module:model/UnifiedErrorMessage} errors
   */
  errors = undefined;
}
