/**
 * ML Lab Service
 * Functionality to create and manage Lab projects, services, datasets, models, and experiments.
 *
 * OpenAPI spec version: 0.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LabJob from './LabJob';
import UnifiedErrorMessage from './UnifiedErrorMessage';
import UnifiedFormatMetadata from './UnifiedFormatMetadata';

/**
* The LabJobResponse model module.
* @module model/LabJobResponse
* @version 0.2.0-SNAPSHOT
*/
export default class LabJobResponse {
    /**
    * Constructs a new <code>LabJobResponse</code>.
    * @alias module:model/LabJobResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>LabJobResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LabJobResponse} obj Optional instance to populate.
    * @return {module:model/LabJobResponse} The populated <code>LabJobResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LabJobResponse();
                        
            
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = UnifiedFormatMetadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = LabJob.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = UnifiedErrorMessage.constructFromObject(data['errors']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UnifiedFormatMetadata} metadata
    */
    'metadata' = undefined;
    /**
    * @member {module:model/LabJob} data
    */
    'data' = undefined;
    /**
    * @member {module:model/UnifiedErrorMessage} errors
    */
    'errors' = undefined;




}
