/**
 * ML Lab Service
 * Functionality to create and manage Lab projects, services, datasets, models, and experiments.
 *
 * OpenAPI spec version: 0.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LabProjectConfig model module.
 * @module model/LabProjectConfig
 * @version 0.2.0-SNAPSHOT
 */
export default class LabProjectConfig {
  /**
   * Constructs a new <code>LabProjectConfig</code>.
   * @alias module:model/LabProjectConfig
   * @class
   */

  constructor() {}

  /**
   * Constructs a <code>LabProjectConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LabProjectConfig} obj Optional instance to populate.
   * @return {module:model/LabProjectConfig} The populated <code>LabProjectConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LabProjectConfig();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(
          data['description'],
          'String'
        );
      }
      if (data.hasOwnProperty('visibility')) {
        obj['visibility'] = ApiClient.convertToType(
          data['visibility'],
          'String'
        );
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  name = undefined;
  /**
   * @member {String} description
   */
  description = undefined;
  /**
   * @member {String} visibility
   */
  visibility = undefined;
}
