/**
 * ML Lab Service
 * Functionality to create and manage Lab projects, services, datasets, models, and experiments.
 *
 * OpenAPI spec version: 0.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LabScheduledJob model module.
 * @module model/LabScheduledJob
 * @version 0.2.0-SNAPSHOT
 */
export default class LabScheduledJob {
  /**
   * Constructs a new <code>LabScheduledJob</code>.
   * @alias module:model/LabScheduledJob
   * @class
   */

  constructor() {}

  /**
   * Constructs a <code>LabScheduledJob</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LabScheduledJob} obj Optional instance to populate.
   * @return {module:model/LabScheduledJob} The populated <code>LabScheduledJob</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LabScheduledJob();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('jobName')) {
        obj['jobName'] = ApiClient.convertToType(data['jobName'], 'String');
      }
      if (data.hasOwnProperty('dockerImage')) {
        obj['dockerImage'] = ApiClient.convertToType(
          data['dockerImage'],
          'String'
        );
      }
      if (data.hasOwnProperty('configuration')) {
        obj['configuration'] = ApiClient.convertToType(data['configuration'], {
          String: 'String',
        });
      }
      if (data.hasOwnProperty('schedule')) {
        obj['schedule'] = ApiClient.convertToType(data['schedule'], 'String');
      }
      if (data.hasOwnProperty('addedAt')) {
        obj['addedAt'] = ApiClient.convertToType(data['addedAt'], 'Number');
      }
      if (data.hasOwnProperty('lastExecution')) {
        obj['lastExecution'] = ApiClient.convertToType(
          data['lastExecution'],
          'Number'
        );
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  id = undefined;
  /**
   * @member {String} jobName
   */
  jobName = undefined;
  /**
   * @member {String} dockerImage
   */
  dockerImage = undefined;
  /**
   * @member {Object.<String, String>} configuration
   */
  configuration = undefined;
  /**
   * @member {String} schedule
   */
  schedule = undefined;
  /**
   * @member {Number} addedAt
   */
  addedAt = undefined;
  /**
   * @member {Number} lastExecution
   */
  lastExecution = undefined;
}
