/*
 * ML Lab Service
 * Functionality to create and manage Lab projects, services, datasets, models, and experiments.
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MlLabService) {
      root.MlLabService = {};
    }
    root.MlLabService.LabScheduledJob = factory(root.MlLabService.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The LabScheduledJob model module.
   * @module model/LabScheduledJob
   * @version 2.2.0-SNAPSHOT
   */

  /**
   * Constructs a new <code>LabScheduledJob</code>.
   * @alias module:model/LabScheduledJob
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>LabScheduledJob</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LabScheduledJob} obj Optional instance to populate.
   * @return {module:model/LabScheduledJob} The populated <code>LabScheduledJob</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('jobName'))
        obj.jobName = ApiClient.convertToType(data['jobName'], 'String');
      if (data.hasOwnProperty('dockerImage'))
        obj.dockerImage = ApiClient.convertToType(data['dockerImage'], 'String');
      if (data.hasOwnProperty('configuration'))
        obj.configuration = ApiClient.convertToType(data['configuration'], {'String': 'String'});
      if (data.hasOwnProperty('schedule'))
        obj.schedule = ApiClient.convertToType(data['schedule'], 'String');
      if (data.hasOwnProperty('addedAt'))
        obj.addedAt = ApiClient.convertToType(data['addedAt'], 'Number');
      if (data.hasOwnProperty('lastExecution'))
        obj.lastExecution = ApiClient.convertToType(data['lastExecution'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} jobName
   */
  exports.prototype.jobName = undefined;

  /**
   * @member {String} dockerImage
   */
  exports.prototype.dockerImage = undefined;

  /**
   * @member {Object.<String, String>} configuration
   */
  exports.prototype.configuration = undefined;

  /**
   * @member {String} schedule
   */
  exports.prototype.schedule = undefined;

  /**
   * @member {Number} addedAt
   */
  exports.prototype.addedAt = undefined;

  /**
   * @member {Number} lastExecution
   */
  exports.prototype.lastExecution = undefined;

  return exports;

}));
