/**
 * ML Lab Service
 * Functionality to create and manage Lab projects, services, datasets, models, and experiments.
 *
 * OpenAPI spec version: 0.2.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LabUser model module.
 * @module model/LabUser
 * @version 0.2.0-SNAPSHOT
 */
export default class LabUser {
  /**
   * Constructs a new <code>LabUser</code>.
   * @alias module:model/LabUser
   * @class
   */

  constructor() {}

  /**
   * Constructs a <code>LabUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LabUser} obj Optional instance to populate.
   * @return {module:model/LabUser} The populated <code>LabUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LabUser();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('permissions')) {
        obj['permissions'] = ApiClient.convertToType(data['permissions'], [
          'String',
        ]);
      }
      if (data.hasOwnProperty('attributes')) {
        obj['attributes'] = ApiClient.convertToType(data['attributes'], {
          String: Object,
        });
      }
      if (data.hasOwnProperty('lastActivity')) {
        obj['lastActivity'] = ApiClient.convertToType(
          data['lastActivity'],
          'Number'
        );
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  id = undefined;
  /**
   * @member {String} name
   */
  name = undefined;
  /**
   * @member {Array.<String>} permissions
   */
  permissions = undefined;
  /**
   * @member {Object.<String, Object>} attributes
   */
  attributes = undefined;
  /**
   * @member {Number} lastActivity
   */
  lastActivity = undefined;
}
