/*
 * ML Lab Service
 * Functionality to create and manage Lab projects, services, datasets, models, and experiments.
 *
 * OpenAPI spec version: 2.2.0-SNAPSHOT
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MlLabService) {
      root.MlLabService = {};
    }
    root.MlLabService.ValueListFormatMetadata = factory(root.MlLabService.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ValueListFormatMetadata model module.
   * @module model/ValueListFormatMetadata
   * @version 2.2.0-SNAPSHOT
   */

  /**
   * Constructs a new <code>ValueListFormatMetadata</code>.
   * @alias module:model/ValueListFormatMetadata
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ValueListFormatMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ValueListFormatMetadata} obj Optional instance to populate.
   * @return {module:model/ValueListFormatMetadata} The populated <code>ValueListFormatMetadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('itemCount'))
        obj.itemCount = ApiClient.convertToType(data['itemCount'], 'Number');
      if (data.hasOwnProperty('stats'))
        obj.stats = ApiClient.convertToType(data['stats'], {'String': Object});
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Number');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Number');
      if (data.hasOwnProperty('query'))
        obj.query = ApiClient.convertToType(data['query'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} itemCount
   */
  exports.prototype.itemCount = undefined;

  /**
   * @member {Object.<String, Object>} stats
   */
  exports.prototype.stats = undefined;

  /**
   * @member {Number} limit
   */
  exports.prototype.limit = undefined;

  /**
   * @member {Number} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * @member {Number} time
   */
  exports.prototype.time = undefined;

  /**
   * @member {String} query
   */
  exports.prototype.query = undefined;

  return exports;

}));
