name: reuse-compliance-check
on: workflow_dispatch

jobs:
  reuse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: reuse-compliance-check
        uses: fsfe/reuse-action@v1.1
